services:
  db:
    container_name: database
    image: mysql:8.3.0
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: you_dont_deserve_to_live
      MYSQL_RANDOM_ROOT_PASSWORD: true
    networks:
      - just_dance

  phpmyadmin:
    container_name: php_my_admin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8000:80"
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: you_dont_deserve_to_live
    depends_on:
      - db
    networks:
      - just_dance

  php:
    container_name: apache
    build: .
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    links:
      - db
    networks:
      - just_dance
    stdin_open: true
    tty: true

networks:
  just_dance:
    driver: bridge
volumes:
  db_data:


